= FAQ
:awestruct-layout: two-column
:toc: 


toc::[]

== What is a BaaS?

BaaS stands for Backend-as-a-Service. BaaS are becoming
more popular as application development is moving towards
smarter clients, such as smart-phones, tablets, and even
desktops, running rich clients inside of browsers.

Since the primary focus of application development is 
newer technologies closer to the end-user, the desire
to stop writing as much back-end server code has increased.

A BaaS aims to provide an array of services, ready-to-go,
to support these richer clients.

== I never have to write server-side code again?

A BaaS does not necessarily make that promise, but 
the idea is that for the 80% case of modern applications
targeting mobile and browser clients, significantly
less server-side code needs to be created.

== I can't write server-side code now?

You absolutely can write server-side code to run within
LiveOak.  Since LiveOak has taken a very RESTful view of 
the world, the API for writing server-side services 
is pretty slim. You can implement new resources very
easily and deploy them within an instance of LiveOak.

== How mature is LiveOak?

LiveOak is pretty nascent at the moment.  Being a Red Hat
project, we prefer to be as open as possible, as early as
possible. Thus, at the current moment, LiveOak has few
services and hasn't been battle-tested.

The only way to play with LiveOak currently is to build it
from source.

== What about browser push?

The LiveOak team has taken REST beyond simple HTTP.
REST, of course, stands for Representational State
Transfer.  Resources are active things that live on the
server, and clients communicate with them using representations
of those things. Nothing in the definition of REST
implies using *pure* HTTP.

To that end, LiveOak has embraced WebSockets and other
active technologies to provide *push* style REST. In 
addition to the typical REST verbs that relate to CRUD 
operations (and HTTP verbs), LiveOak adds the concept of 
*SUBSCRIBE*.

Clients can not just create, read, update, and delete
resources, but they can register an interest in any
resource, using RESTful addressing, and be notified
of changes (and updates, and deletions) of those resources,
in real-time.

LiveOak goes beyond just WebSockets to the browser, though,
and supports *any* client that can speak the STOMP protocol.
This enabled command-line tools and other scripts to
watch the system without having to learn how to speak WebSockets.

== How is LiveOak built?

LiveOak is a Java-based server.  Since modern rich clients
are new and fancy, we decided to continue the new-and-fancy
theme and use Java 8.  Java 8 brings some syntactic sugar,
especially when writing asynchronous code, in the form of
lambdas.

To actually build LiveOak, Maven 3 is required.

== What do you mean "asynchronous"?

Given that rich clients want to have continuous connections
to receive real-time updates, they represent a rather large
load on a server, even when no data is flowing.  With traditional
synchronous programming models, this requires threads to be 
blocked, ready-and-waiting to shovel some data to or from the
client.  Each thread has a cost.

Using asynchronous libraries, such as Netty and Vert.x, 
LiveOak can reduce this overhead, and easily support many
thousands of idle connections without becoming overloaded.

== What is the license of LiveOak?

LiveOak is licensed under the 
link:/license[Eclipse Public License version 1.0].  
A copy of the license can be found in the source repository and with our distribution.

