= Manually Configuring an Application for Scripting
:awestruct-layout: two-column
:toc:

toc::[]

== Overview

It is possible to manually modify an application to add in scripting support by setting up a couple of configuration files. 

The various scripting examples (https://github.com/liveoak-io/liveoak-examples/tree/master/scripting) are good examples which already use this approach.

There are a few steps requires to do this, including: configuring the application.json file, adding the script's metadata configuration file and adding the scripts source javascript file.

NOTE: This document assumes that you already have an application configured and just need to add scripting support. It does not cover creating an new application from scratch.

NOTE: Unlike specifying the metadata through the REST interface, specifying the metadata through the filesystem will require the server to be restarted before the changes take effect. Modifying the metadata throught the REST interface will overwrite the metadata stored on the filesystem

== Configuring application.json

To add in scripting support to your application, you will need to add the following to your application.json file:

```
resources: {
    ...
    scripts: {
        type: "scripts",
        config: {
                script-directory: "${application.dir}/scripts"
        }
    },
    ...  
```

This will specify that your application requires the _'scripts'_ module and it should look in the _'script-directory'_ location for the scripts to use.

== Adding Scripts

In order to manually add scripts through configuration files, you will need to add some configuration files.

For **resource-triggered scripts**, you will need to add two configuration files: one to manage the scripts metadata and another to contain the script itself.

```
${script-directory}/resource-based/${id}/metadata.json
${script-directory}/resource-based/${id}/source.js
```

For **sheduled scripts**, you will need to add two configuration files: one to manage the scripts metadata and another to contain the script itself.

```
${script-directory}/scheduled/${id}/metadata.json
${script-directory}/scheduled/${id}/source.js
```

For **endpoint scripts**, you will need to add two configuration files: one to manage the scripts metadata and another to contain the script itself.

```
${script-directory}/endpoint/${id}/metadata.json
${script-directory}/endpoint/${id}/source.js
```

NOTE:
* +${script-directory}+ is the _script-directory_ specified in the application.json file.
* +${id}+ is the id value for your particular script.

=== Examples metadata.json

The following is an example of what could be contained in the metadata.json file. It is taken from the link:https://github.com/liveoak-io/liveoak-examples/tree/master/scripting/helloscript[helloscript] example

For more information about the metadata for resource triggered scripts, see the link:/docs/reference/scripting/resource_triggered_scripts[Resource-Triggered Scripts] documentation.

```
{
  "libraries" : [ "client" ],
  "name" : "HelloWorldScript",
  "description" : "Simple script to add a message to the log whenever any resource is read",
  "target-path" : "/helloscript/**",
  "enabled" : true,
  "priority" : 1
}
```

=== Example source.js

The following is an example of what could be contained in the source.js file. It is taken from the link:https://github.com/liveoak-io/liveoak-examples/tree/master/scripting/helloscript[helloscript] example

For more information about the source files for resoure-triggered scripts, see the link:/docs/reference/scripting/resource_triggered_scripts[Resource-Triggered Scripts] documentation.


```
function preRead(request, libraries) {
	print("Hello incoming request for " + request.path);
}

function postRead(response, libraries) {
	print("Goodbye outgoing response for " + response.request.path);
}
```
