= Resource Triggered Scripts
:awestruct-layout: two-column
:toc:

toc::[]

== Overview

These scripts get triggered before and/or after a resource invocation. This includes the resource CRUD operations as well as when a resource invocation results in an error.


These types of scripts are useful for such things as:

* Verifying the data entering the system is properly formated
* Acting as a highly customizable gatekeeper to resources
* Modifying incoming requests and outgoing responses.
* Triggering other events based on a resource state.


== Metadata

Resource-triggered scripts have metadata associated with them which is used to configure the behaviour of the script.

[format="dsv",cols="1,5,1,1,1",frame="topbot",options="header"]
|======================
Field:Description:Type:Options:Default
+name+: User readable name for the script.: String: Optional:
+description+: User readable description for the script.: String: Optional:
+target-path+: Specifies the type of target the script should be applied to.: String: Required:
+priority+: The priority in which this script should be run.: Number: Optional:1
+enabled+: If the script is currently set to run or not.: Boolean: Optional:true
+libraries+: Any extra libraries the script may required.: String Array: Optional
|======================


=== Target-Path

The target path is used to denote which resources should trigger this particular script. This does not follow regular expressions, but instead must follow a specific syntax:


[format="dsv",cols="1,3",frame="topbot",options="header"]
|======================
Path:Targeted Resource
+/foo/bar/baz+: Targets one particular resource
+/foo/bar/*+: Targets the children of one particular resource
+/foo/bar/baz/**+: Targets all the descendants of one particular resource
+/**+: Targets all descendens of the application
|======================

=== JSON Example

The following is an example of the metadata for a particular resource represented in a JSON format. For this example, it is configured to be run against all resources under the application, and request the inclusion of the client library.

```
{
   "name" : "Hello World Script",
  "description" : "This script prints to the log a welcome message with the resource path whenever any resource in the application is read.",
  "enabled" : true,
  "target-path" : "/**",
  "priority" : 1,
  "libraries" : [ "client" ],
}

```

== Script

=== Functions

When the resource triggered script is first loaded or updated, its functions are read to see that types of triggers are applicable for calling the script.

The types of triggers can be for before or after any of the create, read, update & delete operations as well as when an error occurs during a resource invocation.

The following are the function definitions which define these triggers:

[format="dsv",cols="1,4",frame="topbot",options="header"]
|======================
Type:Function
+pre-create+: function preCreate(request, libraries) {...}
+post-create+: function postCreate(response, libraries) {...}
+pre-read+: function preRead(request, libraries) {...}
+post-read+: function postRead(response, libraries) {...}
+pre-update+: function preUpdate(request, libraries) {...}
+post-update+: function postUpdate(response, libraries) {...}
+pre-delete+: function preDelete(request, libraries) {...}
+post-delete+: function postDelete(response, libraries) {...}
+on-error+: function onError(response,libraries) {...}
|======================


