= Beta01
Ken Finnigan

We are proud to announce the first public beta release of link:http://liveoak.io[LiveOak]!

== Release Highlights

Some of the highlights of Beta01 are:

* Application configuration via git
* Business Logic creation and script editing within the Console
* LiveOak examples are now installable directly from GitHub within the Console
* Pagination of Resources with links
* Improved UX for Security Policies within the Console

Along with many other improvements and bug fixes.

For a full list of all the resolved issues, see the link:https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12314622&version=12323825[Release Notes].

=== Git integration

There are a few git related enhancements for this release:

* Each application that is created, installed, or imported through the Console will now have a git repository created for it, with all changes to the
configuration made through the Console committed as a single unit of work.

* Applications can now be installed from git, within the Console, by providing an http(s) url pointing to the git repository. This is now how the LiveOak
examples are installed, ensuring that whenever they are installed, the user is getting the most recent version. It's also a convenient way to move a LiveOak
application between environments.

=== Business Logic

The Console now provides the ability to create and edit Business Logic scripts directly. Part of this functionality is a code editor within the Console that
provides feedback on the validity of the javascript that was entered.

== On the way to 1.0.0.Final?

Some of the key features we're looking to introduce before we go final:

* API usage metrics and basic analytics
* SDKs and tooling
* Continued UX improvements to the Console


Please link:/downloads[download it] and link:/docs/#getting-started[try it out], then go to our link:/community[community page],
subscribe to the mailing list and share your feedback!
