:awestruct-layout: doc
:awestruct-doc_nav_partial: doc_android_nav.html.haml
:linkattrs:

[[installing-android]]
== Installing Android SDK Tools

Visit the http://developer.android.com/sdk/index.html[official Android SDK site].

We recommend downloading the `Android Studio`, as we believe it's the best way to develop Android applications. However,
we only require that you have the `SDK Tools` installed to be able to build the android examples. If you would prefer
to only install the `SDK Tools`, go http://developer.android.com/sdk/installing/index.html[here] and select to download
the `Stand-alone SDK Tools`.

After downloading `Android Studio`, or `SDK Tools`, you have to run the `android` configuration tool to install the
initial platform SDK, and build tools.

=== Fedora 20

After downloading a linux .tgz archive unpack it. The newly created directory is your ANDROID_HOME. For example:

[source,bash]
----
cd /opt
su -c 'tar xvzf ~/Downloads/android-sdk_r24.0.2-linux.tgz'
export ANDROID_HOME=/opt/android-sdk-linux
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
----

Now run the `android` tool as a superuser:

[source,bash]
----
su -c android
----

=== Ubuntu

After downloading a linux .tgz archive unpack it. The newly created directory is your ANDROID_HOME. For example:

[source,bash]
----
cd /opt
sudo tar xvzf ~/Downloads/android-sdk_r24.0.2-linux.tgz
export ANDROID_HOME=/opt/android-sdk-linux
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
----

Now run the `android` tool as a superuser:

[source,bash]
----
sudo android
----

You may later need to fix ownership of ~/.android directory:

[source,bash]
----
sudo chown -R $(whoami):$(whoami) ~/.android
----

=== Mac OS X

After downloading a Mac OS X .zip archive unpack it. The newly created directory is your ANDROID_HOME. For example:

[source,bash]
----
cd /opt
sudo tar xvzf ~/Downloads/android-sdk_r24.0.2-macosx.tgz
export ANDROID_HOME=/opt/android-sdk-macosx
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
----

Now run the `android` tool as a superuser:

[source,bash]
----
sudo android
----

=== Windows

Download the installer .exe bundle, and run it to perform installation. When done, 'Android SDK Manager' should open up automatically.
If it doesn't, use the Windows Start button, and type `SDK Manager` in a search box. That should find it so you can start it.

[[build-tools]]
=== Installing Android platforms, and Build Tools

When ‘android’ tool starts, make sure to mark for installation the `Android 4.4.2 (API 19)`, and `Android SDK Build-Tools` version '19.1'.

You can leave other options as they are.

Then press ‘Install XX packages’ button to download, and install the packages.

You need to accept all the licences for all components to be installed.

=== Other Tools

'Android SDK' supports different build tools, which don't come as part of the download.

One needed when using 'Cordova' is link:/docs/install/ant[Apache Ant]. Make sure to install `ant` before building 'Cordova' examples.
