:awestruct-layout: doc
:linkattrs:
:icons: font

== Getting Started

[[gs-overview]]
=== Overview

As developer interest moves to creating rich applications for mobile handsets, tablets, or any device using HTML5
and Javascript, the need for server-side code is significantly reduced.

LiveOak is all about making it easier to develop mobile client applications by providing ready made, easy to consume cloud
services that most mobile applications today require.

Our goal is to enable you, a mobile application developer, to focus on developing an amazing mobile application quickly.
To that end, we provide a "point and click" interface for specifying the services you need for your mobile application.

To enable quicker development of applications that are almost 100% client-side, LiveOak provides both the typically-needed
services like data persistence out of the box, along with a platform and API for providing your own custom services. Additional
services may be created and deployed by 3rd-party service-providers, or as little blobs of custom server-side code explicitly in
support of a specific application.

LiveOak can be deployed locally on a developer machine, or in the cloud - either to OpenShift Online or as a Docker container.

=== REST with 100% more push

HTML5/Javascript-based applications today have a variety of libraries and frameworks that enable interaction with RESTful
services, typically via JSON.  LiveOak fully supports RESTful interactions, with strong following of the Fielding Constraints.

At least with HTTP 1.1, the polling nature of REST is not necessarily as performant and reactive as applications would desire.
Strategies such as long-polling have worked around this in the past. WebSockets and Server-Sent Events (SSE) now provide
alternatives for pushing bits from the server to the client in real-time. LiveOak has overlaid RESTful concepts on top
of these push technologies.

This addition of push semantics basically adds one more verb to the standard array of REST verbs: SUBSCRIBE.

For any given resource provided by the LiveOak server, in addition to traditional GET, POST, PUT and DELETE, a client can SUBSCRIBE
to the same resource, and be immediately notified of changes to the resource, including creates, updates, and deletes.

=== A Resource

The only type of component visible on the server-side is a *Resource*, which matches the ideas of REST. Each resource is
addressable through a URL, and may (or may not) support the full array of CRUD operations. Each resource may have a set
of properties and may have a set of children.

include::docs/install/_liveoak.adoc[]

[[gs-screencasts]]
=== Screencasts

Here are some screencasts that we've put together to help you become familiar with what LiveOak can do:

- https://vimeo.com/96213933[Rapid application development with LiveOak (Part 1) - HTML Chat client]
- https://vimeo.com/96691967[Rapid application development with LiveOak (Part 2) - Security]
- https://vimeo.com/jbossdeveloper/review/105402526/9797d7a3b8[Installing LiveOak examples - With the Admin Console]
- https://vimeo.com/106071915[LiveOak Business Logic (Part 1) - Introduction to resource triggered scripting]
- https://vimeo.com/106072405[LiveOak Business Logic (Part 2) - Using the LiveOak Client]

== Examples

LiveOak comes with some example applications that are installable from within the Admin Console.

include::docs/examples/_chat-html.adoc[]

include::docs/examples/_chat-android.adoc[]

include::docs/examples/_chat-ios.adoc[]

include::docs/examples/_chat-secured.adoc[]

include::docs/examples/_business-logic.adoc[]

[[ex-todo]]
=== ToDo

This is a famous http://todomvc.com[ToDoMVC] example implemented using LiveOak as a backend. It uses storage service, but
also demonstrates basic security configuration - creating users, and using roles to restrict access to particular task lists.

The example comes in two forms:

* As an link:/docs/#ex-todo-html[HTML web application]

* As an link:/docs/#ex-todo-cordova[Android application] - implemented using Apache Cordova.

include::docs/examples/_todo-html.adoc[]

include::docs/examples/_todo-cordova.adoc[]

[[ex-gallery]]
=== Gallery

Gallery is a simple image gallery allowing browsing and uploading of photos. It demonstrates LiveOak's binary data
storage capabilities.

The example comes in two forms:

* As an link:/docs/#ex-gallery-html[HTML web application]

* As an link:/docs/#ex-gallery-cordova[Android application] - implemented using Apache Cordova.

include::docs/examples/_gallery-html.adoc[]

include::docs/examples/_gallery-cordova.adoc[]

include::docs/examples/_basic-auth.adoc[]

== Dashboard

[[create-app]]
=== Creating a new Application

NOTE: Updated documentation coming soon.

[[install-examples]]
=== Install Examples

NOTE: Updated documentation coming soon.

[[security]]
=== Security

NOTE: Updated documentation coming soon.

[[storage]]
=== Data Storage

NOTE: Updated documentation coming soon.

include::docs/dash/_push.adoc[]

[[clients]]
=== Clients

NOTE: Updated documentation coming soon.

== Developing Apps

include::docs/develop/_subscriptions.adoc[]

== Customising the Server

include::docs/custom/_spi.adoc[]

include::docs/custom/_extensions.adoc[]

== Advanced Topics

include::docs/advanced/_serverconfig.adoc[]

include::docs/advanced/_keycloak.adoc[]

include::docs/advanced/_services.adoc[]

