= Documentation
:awestruct-layout: two-column
:toc:

toc::[]

== Basic Premise

As developer interest moves to creating rich applications
for mobile handsets, tablets, or any device using HTML5
and Javascript, the need for server-side code is significantly
reduced.

To enable quicker development of applications that are almost 100% client-side,
LiveOak provides both the typically-needed services like data persistence out
of the box, along with a platform and API for providing your own custom
services.  Additional services may be created and deployed by 3rd-party
service-providers, or as little blobs of custom server-side code explicitly in
support of a specific application.

=== REST with 100% more push

HTML5/Javascript-based applications today have a variety of
libraries and frameworks that enable interaction with RESTful
services, typically JSON.  LiveOak fully supports RESTful
interactions, with strong following of the Fielding Constraints.

At least with HTTP 1.1, the polling nature of REST is not
necessarily as performant and reactive as applications would
desire. Strategies such as long-polling have worked around this
in the past.  WebSockets and Server-Sent Events (SSE) now provide
alternatives for pushing bits from the server to the client 
in real-time. LiveOak has overlaid RESTful concepts on top
of these push technologies. 

This addition of push semantics basically adds one more verb
to the standard array of REST verbs:  SUBSCRIBE.

For any given resource provided by the LiveOak server, in addition
to traditional GET, POST, PUT and DELETE, a client can SUBSCRIBE
to the same resource, and be immediately notified of changes
to the resource, including creates, updates, and deletes.

=== A Resource

The only type of component visible on the server-side is a *Resource*,
which matches the ideas of REST.  Each resource is addressable
through a URL, and may (or may not) support the full array of
CRUD operations. Each resource may have a set of properties
and may have a set of children.

Resources are controlled by Extensions, described more fully below.

== Launching LiveOak

=== Standalone

To launch LiveOak, use `bin/liveoak`.  By default, it
binds to localhost on port 8080.

== All About Resources

=== Properties

=== Members

== All About Subscriptions

The LiveOak BaaS supports subscribing to resources, in order
to be notified about changes to resources. A subscription is 
of course just another resource.  Which means, if you want turtles
all the way down, you can subscribe to subscriptions.

A subscription has a path that should match one-or-more resources
and may include the any number of `*` wildcard segments.

Example paths include:

* `/people/*`
* `/people/bob`
* `/states/*/capitals`

Once a subscription is created, LiveOak will pay attention to
resources that match the the subscription path, and provide
notifications of changes (create, update, delete) to resources
that match.

The way notification is delivered is dependent upon which method
for subscribing was used: STOMP or HTTP.

=== Subscribing to resources over STOMP

In the browser, using the LiveOak JavaScript SDK, subscriptions
to resources are created using the `subscribe()` method:

[source,javascript]
liveoak.subscribe( '/people/*', function(person) {
  // fixme, how do we tell what sort of change occurred?
} );

=== Subscribing to resources over HTTP

Subscriptions can also be delivered over HTTP, and these subscriptions
are created over HTTP by creating a subscription resource.

[source]
POST /subscriptions
{ 
  'destination': 'http://myserver.com/my-people/',
  'path': '/people/*'
}

When events occur that matches the subscription path, 
a similar action is performed against the `destination`
URL.  For instance, if a new person resource is created
at `/people/bob`, then your server would receive a `PUT`
at `http://myserver.com/my-people/bob` with the same data.

While the person may have been created using a POST to 
`/people` on the LiveOak server, that is translated to a `PUT`
upon notification so as to ensure matching resource identifiers.

Likewise, if `/people/bob` is deleted from the LiveOak server,
your server would receive a `DELETE` at 
`http://myserver.com/my-people/bob`.

include::extensions.adoc[]

