= Extensions
:awestruct-layout: two-column
:toc:
:toc-placement!:

toc::[]

== What is an Extension?

An Extension is the mechanism used by LiveOak to bring a class
of resource into the system.  An extension is loaded using
JBoss-Modules, and implements `io.liveoak.spi.extension.Extension`.

A given extension may be installed several times under different
names, with different configuration values.

== Responsibilities of an Extension

An extension runs within the context of an initialized LiveOak
server, and has two main roles:

* Initialize resources at a system-wide level
* Initialize resources for each application in which it is used

== System-wide Initialization

When installed, an Extension's first `extend(...)` method is called,
and provided a `SystemExtensionContext`. This context provides
the extension the following:

* The ID under which it is being installed
* An MSC `ServiceTarget` in which to install services
* An MSC `ServiceName` referencing the system-level configuration
  object for the extension.

The extension may choose to install shared MSC services through
the `ServiceTarget` and may inject the configuration to any of
these services.

During system-wide initialization, no actions are required to be
performed for any application wishing to use the extension.

== Application-level Initialization

When an extension is provisioned for a specific application,
its second `extend(...)` method is called, provided an
`ApplicationExtensionContext`.  This context provides the extension
the following:

* The ID under which it is being installed
* An MSC `ServiceTarget` in which to install services
* An MSC `ServiceName` referencing the application-level configuration
  object for the extension
* A reference to the `Application` requesting the extension provisioning.

Additional, two methods are provided for installing Resources into the
web-accessible resource tree:

* `mountPublic(...)`
* `mountPrivate(...)`

Just as with system-level initialization, an Extension may choose
to install many MSC services on behalf of each application that
uses it. It is expected that at least some of these will be web-accessible
`Resource` implementations.

The extension may call `mountPublic(...)` exactly once, with a
`ServiceName` which points to a `RootResource` with the same ID
as the extension-context provides.  This will result in mounting
the resource on the public side of the application's URL-space:

----
http://host.com/some-org/some-app/the-resource
----

An extension may mount zero or more "administrative" resources
on the private side of the application's URL-space.  If the extension
is installed as `foo`, and mounts two resources with IDs of `dog` and
`cat`, they would be available through URLs such as:

----
http://host.com/liveoak/zero/organizations/some-org/applications/some-app/resources/foo/dog

http://host.com/liveoak/zero/organizations/some-org/applications/some-app/resources/foo/cat
----


== Configuration Changes

The configurations for both system-level and application-level are never
provided directly to the extension.  Instead the `ServiceName` of each configuration
object is provided for injection into whatever components require it.

The LiveOak system itself manages updates to this configuration.  When the configuration
is changed, the service providing it becomes temporarily unavailable, and the new configuration
is installed in its place.

If extension services are dependent upon the configuration directly, using
the MSC `addDependency(...)` method, this change of configuration will cause a ripple
of services temporarily going offline, and then coming back up with the new configuration
injected into them.

IMPORTANT: The team is still working on a less catastrophic way to update configuration
without forcing a restart of an entire tree of services.
