= Server Side Scripting
:awestruct-layout: two-column
:toc:
:toc-placement!:

toc::[]

== Overview

LiveOak provides the capability for application developers to write and administer their own javascript logic to run within LiveOak itself.

These scripts allows the application developer to perform such tasks as:

* Inspecting the incoming request and response.
* Modifying the incoming request and response.
* Denying the incoming request or response.
* Accessing any of the LiveOak resources. This allows for such things as reading and writing to the LiveOak storage resources as well as configuring Security settings and setting up things like UPS integration.
* Expose external resources through LiveOak.
* Aggregating content from multiple LiveOak resources or external services
* Performing calculations or complex multistep processes

== Types

There are three main types of server side scripting available in LiveOak

=== link:/docs/reference/scripting/resource_triggered_scripts[Resource-Triggered Scripts]
These types of scripts are triggered before and or after a resource invocation.

=== link:/docs/reference/scripting/scheduled_scripts[Scheduled Scripts]
These types of scripts are triggered based on a schedule and/or repeat over an interval of time

=== link:/docs/reference/scripting/endpoint_scripts[Endpoint Scripts]
These types of scripts open up and expose endpoints for client applications to access.


== Managing Scripts Through the Console

+COMING SOON+

== Advanced

=== link:/docs/reference/scripting/javascript/out/index.html[JavaScript API]
The JavaScript APIs for creating LiveOak Server Side Scripts.

=== link:/docs/reference/scripting/rest[REST Endpoint Specification]
REST endpoint specification for creating/reading/updating/deleting scripts using the scripting REST interface.

=== link:/docs/reference/scripting/manual_configuration[Manually Configuring an Application]
How to manually configure an application for scripting support using configuration files.
